trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'Publish Web API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(Build.SourcesDirectory)/src/WebApiDemo/WebApiDemo/WebApiDemo.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@5
  displayName: 'Deploy to Azure Web App'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'vbu-demo'
    appType: 'webApp'
    WebAppName: 'demo-api'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/WebApiDemo.zip'